# This is a simple ansible playbook for installing packages needed by blivet-gui
# test suites.
# You can do this by using 'make install-requires' or manually using
# 'ansible-playbook -K -i "localhost," -c local install-test-dependencies.yml'
# Currently only Fedora and Debian are supported by this playbook.

---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Install runtime and build dependencies (Fedora)
    package: name={{item}} state=installed
    with_items:
      - gettext
      - python3-setuptools
      - python3
      - python3-gobject
      - gettext
      - python3-blivet
      - gtk3
      - python3-pid
      - make
    when: ansible_distribution == "Fedora"

  - name: Install test dependencies (Fedora)
    package: name={{item}} state=installed
    with_items:
      - python3-coverage
      - python3-pocketlint
      - python3-pycodestyle
      - xorg-x11-server-Xvfb
      - targetcli
      - gettext
      - python3-polib
      - libblockdev-part
    when: ansible_distribution == "Fedora"

  - name: Update apt cache (Debian/Ubuntu)
    apt:
      update_cache: yes
    when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

  - name: Install runtime and build dependencies (Ubuntu/Debian)
    package: name={{item}} state=present
    with_items:
      - debhelper
      - python3-setuptools
      - gettext
      - dh-python
      - python3-gi-cairo
      - gir1.2-gtk-3.0
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - name: Install test dependencies (Ubuntu/Debian)
    package: name={{item}} state=present
    with_items:
      - python3-coverage
      - python3-pycodestyle
      - pycodestyle
      - xvfb
      - targetcli-fb
      - python3-pip
      - gettext
      - python3-polib
      - libblockdev-part2
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - name: Install Blivet dependencies not covered by PyPI (Ubuntu/Debian)
    package: name={{item}} state=present
    with_items:
      - python3-blockdev
      - python3-bytesize
      - python3-parted
      - python3-selinux
      - gir1.2-blockdev-2.0
      - libblockdev-lvm2
      - libblockdev-btrfs2
      - libblockdev-swap2
      - libblockdev-loop2
      - libblockdev-crypto2
      - libblockdev-mpath2
      - libblockdev-dm2
      - libblockdev-mdraid2
      - libblockdev-nvdimm2
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  # pocketlint, blivet and pid is not packaged on Ubuntu/Debian
  - name: Install pocketlint, blivet and pid using pip (Ubuntu/Debian)
    pip:
      name: ['pocketlint', 'blivet', 'pid']
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - name: Install runtime and build dependencies (OpenSUSE)
    package: name={{item}} state=present
    with_items:
      - make
      - appstream-glib
      - polkit
      - python3-setuptools
      - python3-gobject
      - gettext
      - libgtk-3-0
      - typelib-1_0-Gtk-3_0
      - gobject-introspection
      - python3-gobject-Gdk
      - typelib-1_0-Gtk-3_0
    when: ansible_os_family == "Suse"

  - name: Install test dependencies (openSUSE)
    package: name={{item}} state=present
    with_items:
      - python3-coverage
      - python3-pycodestyle
      - xorg-x11-server-Xvfb
      - xvfb-run
      - targetcli-fb
      - python3-pip
      - python3-polib
      - libbd_part2
      - e2fsprogs
      - adwaita-icon-theme
    when: ansible_os_family == "Suse"

  - name: Install Blivet dependencies not covered by PyPI (openSUSE)
    package: name={{item}} state=present
    with_items:
      - python3-libblockdev
      - typelib-1_0-BlockDev-2_0
      - python3-libbytesize
      - python3-parted
      - python3-pyudev
      - python3-six
      - udev
      - libbd_btrfs2
      - libbd_crypto2
      - libbd_dm2
      - libbd_fs2
      - libbd_kbd2
      - libbd_loop2
      - libbd_lvm2
      - libbd_mdraid2
      - libbd_mpath2
      - libbd_swap2
      - libbd_utils2
    when: ansible_os_family == "Suse"

  # pocketlint, blivet and pid is not packaged on openSUSE
  - name: Install pocketlint, blivet and pid using pip (openSUSE)
    pip:
      name: ['pocketlint', 'blivet', 'pid']
    when: ansible_os_family == "Suse"