# This is a simple ansible playbook for installing packages needed by blivet-gui
# test suites.
# You can do this by using 'make install-requires' or manually using
# 'ansible-playbook -K -i "localhost," -c local install-test-dependencies.yml'
# Currently only Fedora and Debian are supported by this playbook.

---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Install runtime and build dependencies (Fedora)
    package: name={{item}} state=installed
    with_items:
      - gettext
      - python3-setuptools
      - python3
      - python3-gobject
      - gettext
      - python3-blivet
      - gtk3
      - python3-pid
      - make
    when: ansible_distribution == "Fedora"

  - name: Install test dependencies (Fedora)
    package: name={{item}} state=installed
    with_items:
      - python3-coverage
      - python3-pocketlint
      - python3-pycodestyle
      - xorg-x11-server-Xvfb
      - targetcli
      - gettext
      - python3-polib
      - libblockdev-part
    when: ansible_distribution == "Fedora"

  - name: Update apt cache (Debian/Ubuntu)
    apt:
      update_cache: yes
    when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

  - name: Install runtime and build dependencies (Ubuntu/Debian)
    package: name={{item}} state=present
    with_items:
      - debhelper
      - python3-setuptools
      - gettext
      - dh-python
      - python3-gi-cairo
      - gir1.2-gtk-3.0
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - name: Install test dependencies (Ubuntu/Debian)
    package: name={{item}} state=present
    with_items:
      - python3-coverage
      - python3-pycodestyle
      - pycodestyle
      - xvfb
      - targetcli-fb
      - python3-pip
      - gettext
      - python3-polib
      - libblockdev-part2
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - name: Install Blivet dependencies not covered by PyPI (Ubuntu/Debian)
    package: name={{item}} state=present
    with_items:
      - python3-blockdev
      - python3-bytesize
      - python3-parted
      - python3-selinux
      - gir1.2-blockdev-2.0
      - libblockdev-lvm2
      - libblockdev-btrfs2
      - libblockdev-swap2
      - libblockdev-loop2
      - libblockdev-crypto2
      - libblockdev-mpath2
      - libblockdev-dm2
      - libblockdev-mdraid2
      - libblockdev-nvdimm2
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  # pocketlint, blivet and pid is not packaged on Ubuntu/Debian
  - name: Install pocketlint, blivet and pid using pip (Ubuntu/Debian)
    pip:
      name: ['pocketlint', 'blivet', 'pid']
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
