actions:
  get-current-version:
    - "python3 ./setup.py --version"
  create-archive:
    - "make local"
    - 'bash -c "ls *.tar*"'

jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-all
  trigger: pull_request

- job: copr_build
  trigger: commit
  owner: "@storage"
  project: blivet-daily
  branch: master
  preserve_project: true

srpm_build_deps:
 - make
 - gettext
 - python3-devel
 - python3-setuptools
 - desktop-file-utils
 - libappstream-glib
