actions:
  get-current-version:
    - "python3 ./setup.py --version"
  create-archive:
    - "make local"
    - 'bash -c "ls *.tar*"'
jobs:
- job: tests
  metadata:
    targets:
    - fedora-all
  trigger: pull_request

srpm_build_deps:
 - make
 - gettext
 - python3-devel
 - python3-setuptools
 - desktop-file-utils
 - libappstream-glib
