name: Static Analysis

on:
  pull_request:
    branches:
     - main
  push:
    branches:
     - main
  schedule:
    - cron: 0 0 * * 0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run:   |
         sudo apt-get -qq update
         sudo apt-get -y -qq install make ansible
         sudo make install-requires
    - name: Run checks
      run: make check

